/**
 *This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.fico.dmp.entitybantravelhistoryservice.controller;

import com.fico.dmp.entitybantravelhistoryservice.EntityBanTravelHistoryService;
import java.lang.Integer;
import java.lang.Exception;
import com.fico.telus.model.BanTravelHistoryModel;
import java.util.List;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/entityBanTravelHistory")
public class EntityBanTravelHistoryController {

    @Autowired
    private EntityBanTravelHistoryService entityBanTravelHistoryService;

    @RequestMapping(value = "/entityBanTravelHistory", method = RequestMethod.GET)
    public List<BanTravelHistoryModel> fetchEntityBanTravelHistory(@RequestParam(value = "id", required = false) Integer id) throws Exception {
        return entityBanTravelHistoryService.fetchEntityBanTravelHistory(id);
    }
}
