-- MIGRATION SCRIPT
-- Database Type: DBType{type='mysql', urlScheme='jdbc:', dialect='org.hibernate.dialect.MySQLDialect', driverClass='org.mariadb.jdbc.Driver'}
-- App Name: TELUSAgentUI
-- Database: TELUSAgentUIDB
-- Created At: 23-Jan-2023 05:19:27.UTC
-- Script Version: 1.1
-- -----------------------------------------------------------------
-- USER SQL SCRIPT