/*Copyright (c) 2020-2021 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.telusagentuidb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetManagerByTeamIdResponse implements Serializable {


    @ColumnAlias("emplId")
    private String emplId;

    @ColumnAlias("id")
    private Long id;

    @ColumnAlias("managerName")
    private String managerName;

    public String getEmplId() {
        return this.emplId;
    }

    public void setEmplId(String emplId) {
        this.emplId = emplId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getManagerName() {
        return this.managerName;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetManagerByTeamIdResponse)) return false;
        final GetManagerByTeamIdResponse getManagerByTeamIdResponse = (GetManagerByTeamIdResponse) o;
        return Objects.equals(getEmplId(), getManagerByTeamIdResponse.getEmplId()) &&
                Objects.equals(getId(), getManagerByTeamIdResponse.getId()) &&
                Objects.equals(getManagerName(), getManagerByTeamIdResponse.getManagerName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmplId(),
                getId(),
                getManagerName());
    }
}