/*Copyright (c) 2020-2021 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.telusagentuidb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetRolesPermissionResponse implements Serializable {


    @ColumnAlias("ID")
    private Long id;

    @ColumnAlias("RoleId")
    private Long roleId;

    @ColumnAlias("PermissionId")
    private Long permissionId;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetRolesPermissionResponse)) return false;
        final GetRolesPermissionResponse getRolesPermissionResponse = (GetRolesPermissionResponse) o;
        return Objects.equals(getId(), getRolesPermissionResponse.getId()) &&
                Objects.equals(getRoleId(), getRolesPermissionResponse.getRoleId()) &&
                Objects.equals(getPermissionId(), getRolesPermissionResponse.getPermissionId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getRoleId(),
                getPermissionId());
    }
}