/*Copyright (c) 2020-2021 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.telusagentuidb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetRolesByGroupIdResponse implements Serializable {


    @ColumnAlias("id")
    private Long id;

    @ColumnAlias("role")
    private String role;

    @ColumnAlias("description")
    private String description;

    @ColumnAlias("active")
    private Boolean active;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetRolesByGroupIdResponse)) return false;
        final GetRolesByGroupIdResponse getRolesByGroupIdResponse = (GetRolesByGroupIdResponse) o;
        return Objects.equals(getId(), getRolesByGroupIdResponse.getId()) &&
                Objects.equals(getRole(), getRolesByGroupIdResponse.getRole()) &&
                Objects.equals(getDescription(), getRolesByGroupIdResponse.getDescription()) &&
                Objects.equals(getActive(), getRolesByGroupIdResponse.getActive());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getRole(),
                getDescription(),
                getActive());
    }
}