/*Copyright (c) 2020-2021 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.telusagentuidb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QueryActivityLogResponse implements Serializable {


    @ColumnAlias("applicationId")
    private Long applicationId;

    @ColumnAlias("applicationNumber")
    private String applicationNumber;

    @ColumnAlias("activityId")
    private Long activityId;

    @ColumnAlias("activityTypeCode")
    private String activityTypeCode;

    @ColumnAlias("activityTypeDesc")
    private String activityTypeDesc;

    @ColumnAlias("activityName")
    private String activityName;

    @ColumnAlias("activityDesc")
    private String activityDesc;

    @ColumnAlias("appStatusId")
    private Long appStatusId;

    @ColumnAlias("appStatusDesc")
    private String appStatusDesc;

    @ColumnAlias("activityStartTime")
    private Timestamp activityStartTime;

    @ColumnAlias("activityEndTime")
    private Timestamp activityEndTime;

    @ColumnAlias("activityDuration")
    private Long activityDuration;

    @ColumnAlias("activityPerformedBy")
    private String activityPerformedBy;

    @ColumnAlias("activityPayloadId")
    private Long activityPayloadId;

    public Long getApplicationId() {
        return this.applicationId;
    }

    public void setApplicationId(Long applicationId) {
        this.applicationId = applicationId;
    }

    public String getApplicationNumber() {
        return this.applicationNumber;
    }

    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber;
    }

    public Long getActivityId() {
        return this.activityId;
    }

    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    public String getActivityTypeCode() {
        return this.activityTypeCode;
    }

    public void setActivityTypeCode(String activityTypeCode) {
        this.activityTypeCode = activityTypeCode;
    }

    public String getActivityTypeDesc() {
        return this.activityTypeDesc;
    }

    public void setActivityTypeDesc(String activityTypeDesc) {
        this.activityTypeDesc = activityTypeDesc;
    }

    public String getActivityName() {
        return this.activityName;
    }

    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    public String getActivityDesc() {
        return this.activityDesc;
    }

    public void setActivityDesc(String activityDesc) {
        this.activityDesc = activityDesc;
    }

    public Long getAppStatusId() {
        return this.appStatusId;
    }

    public void setAppStatusId(Long appStatusId) {
        this.appStatusId = appStatusId;
    }

    public String getAppStatusDesc() {
        return this.appStatusDesc;
    }

    public void setAppStatusDesc(String appStatusDesc) {
        this.appStatusDesc = appStatusDesc;
    }

    public Timestamp getActivityStartTime() {
        return this.activityStartTime;
    }

    public void setActivityStartTime(Timestamp activityStartTime) {
        this.activityStartTime = activityStartTime;
    }

    public Timestamp getActivityEndTime() {
        return this.activityEndTime;
    }

    public void setActivityEndTime(Timestamp activityEndTime) {
        this.activityEndTime = activityEndTime;
    }

    public Long getActivityDuration() {
        return this.activityDuration;
    }

    public void setActivityDuration(Long activityDuration) {
        this.activityDuration = activityDuration;
    }

    public String getActivityPerformedBy() {
        return this.activityPerformedBy;
    }

    public void setActivityPerformedBy(String activityPerformedBy) {
        this.activityPerformedBy = activityPerformedBy;
    }

    public Long getActivityPayloadId() {
        return this.activityPayloadId;
    }

    public void setActivityPayloadId(Long activityPayloadId) {
        this.activityPayloadId = activityPayloadId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QueryActivityLogResponse)) return false;
        final QueryActivityLogResponse queryActivityLogResponse = (QueryActivityLogResponse) o;
        return Objects.equals(getApplicationId(), queryActivityLogResponse.getApplicationId()) &&
                Objects.equals(getApplicationNumber(), queryActivityLogResponse.getApplicationNumber()) &&
                Objects.equals(getActivityId(), queryActivityLogResponse.getActivityId()) &&
                Objects.equals(getActivityTypeCode(), queryActivityLogResponse.getActivityTypeCode()) &&
                Objects.equals(getActivityTypeDesc(), queryActivityLogResponse.getActivityTypeDesc()) &&
                Objects.equals(getActivityName(), queryActivityLogResponse.getActivityName()) &&
                Objects.equals(getActivityDesc(), queryActivityLogResponse.getActivityDesc()) &&
                Objects.equals(getAppStatusId(), queryActivityLogResponse.getAppStatusId()) &&
                Objects.equals(getAppStatusDesc(), queryActivityLogResponse.getAppStatusDesc()) &&
                Objects.equals(getActivityStartTime(), queryActivityLogResponse.getActivityStartTime()) &&
                Objects.equals(getActivityEndTime(), queryActivityLogResponse.getActivityEndTime()) &&
                Objects.equals(getActivityDuration(), queryActivityLogResponse.getActivityDuration()) &&
                Objects.equals(getActivityPerformedBy(), queryActivityLogResponse.getActivityPerformedBy()) &&
                Objects.equals(getActivityPayloadId(), queryActivityLogResponse.getActivityPayloadId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getApplicationId(),
                getApplicationNumber(),
                getActivityId(),
                getActivityTypeCode(),
                getActivityTypeDesc(),
                getActivityName(),
                getActivityDesc(),
                getAppStatusId(),
                getAppStatusDesc(),
                getActivityStartTime(),
                getActivityEndTime(),
                getActivityDuration(),
                getActivityPerformedBy(),
                getActivityPayloadId());
    }
}