/**
 *This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.fico.dmp.fdoutilityservices.controller;

import com.fico.dmp.fdoutilityservices.FDOUtilityServices;
import defaulttermlibrary.Application;
import javax.servlet.http.HttpServletRequest;
import java.lang.Object;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/fDOUtilityServices")
public class FDOUtilityServicesController {

    @Autowired
    private FDOUtilityServices fDOUtilityServices;

    @RequestMapping(value = "/callFDODemo", method = RequestMethod.POST)
    public ResponseEntity<Object> callFDODemo(@RequestBody Application application, HttpServletRequest request) {
        return fDOUtilityServices.callFDODemo(application, request);
    }
}
