/*Copyright (c) 2020-2021 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.telusagentuidb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * QrtzSimpleTriggers generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`QRTZ_SIMPLE_TRIGGERS`")
@IdClass(QrtzSimpleTriggersId.class)
public class QrtzSimpleTriggers implements Serializable {


    private String schedName;

    private String triggerName;

    private String triggerGroup;

    private long repeatCount;

    private long repeatInterval;

    private long timesTriggered;

    @Id
    @Column(name = "`SCHED_NAME`", nullable = false, length = 120)
    public String getSchedName() {
        return this.schedName;
    }

    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    @Id
    @Column(name = "`TRIGGER_NAME`", nullable = false, length = 200)
    public String getTriggerName() {
        return this.triggerName;
    }

    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    @Id
    @Column(name = "`TRIGGER_GROUP`", nullable = false, length = 200)
    public String getTriggerGroup() {
        return this.triggerGroup;
    }

    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    @Column(name = "`REPEAT_COUNT`", nullable = false, scale = 0, precision = 19)
    public long getRepeatCount() {
        return this.repeatCount;
    }

    public void setRepeatCount(long repeatCount) {
        this.repeatCount = repeatCount;
    }

    @Column(name = "`REPEAT_INTERVAL`", nullable = false, scale = 0, precision = 19)
    public long getRepeatInterval() {
        return this.repeatInterval;
    }

    public void setRepeatInterval(long repeatInterval) {
        this.repeatInterval = repeatInterval;
    }

    @Column(name = "`TIMES_TRIGGERED`", nullable = false, scale = 0, precision = 19)
    public long getTimesTriggered() {
        return this.timesTriggered;
    }

    public void setTimesTriggered(long timesTriggered) {
        this.timesTriggered = timesTriggered;
    }




    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QrtzSimpleTriggers)) return false;
        final QrtzSimpleTriggers qrtzSimpleTriggers = (QrtzSimpleTriggers) o;
        return Objects.equals(getSchedName(), qrtzSimpleTriggers.getSchedName()) &&
                Objects.equals(getTriggerName(), qrtzSimpleTriggers.getTriggerName()) &&
                Objects.equals(getTriggerGroup(), qrtzSimpleTriggers.getTriggerGroup());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSchedName(),
                getTriggerName(),
                getTriggerGroup());
    }
}